<?php
// $Id: hcard.module,v 1.1.4.2 2009/01/18 07:06:02 shawndearmond Exp $

/**
 * @file
 * Creates an hCard block.
 */

/**
 * Implementation of hook_help().
 */
function hcard_help($path, $arg) {
  switch ($path) {
    case 'admin/help#hcard':
      $output = '<p>'. t("The hcard is a small bundle of code that you want to put on your web site so that Google Local (and other local search engines) can more easily index the site's location information.") .'</p>';
      $output .= '<p>'. t('Configure your hcard block at the hcard settings page.') .'</p>';
      return $output;
    case 'admin/settings/hcard':
      return '<p>'. t('Enter your site\'s information into the appropriate fields.') .'</p>';
  }
}


/**
 * Implementation of hook_menu().
 */
function hcard_menu() {
    $items['admin/settings/hcard'] = array(
      'title' => 'hCard',
      'description' => 'Configure the hCard block.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('hcard_admin_settings'),
      'access arguments' => array('administer site configuration'),
    );
  return $items;
}

/**
 * Implementation of hook_theme().
 */
function hcard_theme($existing, $type, $theme, $path) {
  return array(
    'hcard_admin_settings' => array(
      'arguments' => array('form' => NULL),
    ),
    'hcard' => array(
      'arguments' => array(
        'hcard' => NULL,
        'given_name' => NULL,
        'family_name' => NULL,
        'org' => NULL,
        'tagline' => NULL,
        'street_address' => NULL,
        'locality' => NULL,
        'region' => NULL,
        'postal_code' => NULL,
        'country' => NULL,
        'longitude' => NULL,
        'latitude' => NULL,
        'phones' => array(),
        'faxes' => array(),
        'category_links' => array(),
        ),
      'template' => 'hcard',
    ),
  );
}

/**
 * Theme preprocess function for the hcard hook
 * @param $variables as defined by hook_theme().
 *        $variable['hcard'] is equivalent to variable_get('hcard', array())
 */
function template_preprocess_hcard(&$variables) {
// Creates a randomizer seed based on the month and the length of the current URL.
// This is used to randomize the categories so that they're different on every page,
// but the output on any particular display only changes once per month.
  $month = date("n");
  $path = request_uri();
  $nid = is_numeric(arg(1)) ? arg(1) : 1;
  $seed = drupal_strlen($path) * $month * $nid;
  srand($seed);

// Build $variables from scratch
  $hcard = $variables['hcard'];
  $variables['given_name'] = $hcard['fn_n']['given-name'] ? l($hcard['fn_n']['given-name'], '<front>') : NULL;
  $variables['family_name'] = $hcard['fn_n']['family-name'] ? l($hcard['fn_n']['family-name'], '<front>') : NULL;
  $variables['org'] = $hcard['org'] ? l($hcard['org'], '<front>') : NULL;
  $variables['street_address'] = check_plain($hcard['adr']['street-address']);
  $variables['locality'] = check_plain($hcard['adr']['locality']);
  $variables['region'] = check_plain($hcard['adr']['region']);
  $variables['postal_code'] = check_plain($hcard['adr']['postal-code']);
  $variables['country'] = check_plain($hcard['adr']['country-name']);
  $variables['longitude'] = check_plain($hcard['longitude']);
  $variables['latitude'] = check_plain($hcard['latitude']);

// Generates the output for the 'tagline' variable.
  if ($hcard['tagline']['tag']) {
    $tag_list = check_plain($hcard['tagline']['tag_list']);
    $tag_list = explode(',', $tag_list);
    $tag_list = array_map('trim', $tag_list);
    $counter = 0;
    $tag_links = array();
    foreach ($tag_list as $tag) {
      $counter++;
      $tag_links['!'. $counter] = l($tag, '<front>');
    }
    $tag = check_plain($hcard['tagline']['tag']);
    $variables['tagline'] = t($tag, $tag_links);
  }

// Generates the output for the 'phones' variable.
  if ($hcard['phone']['voice']) {
    $phone_text = check_plain($hcard['phone']['voice']);
    $phones = explode(',', $phone_text);
    $variables['phones'] = array_map('trim', $phones);
  }

// Generates the output for the 'faxes' variable.
  if ($hcard['phone']['fax']) {
    $fax_text = check_plain($hcard['phone']['fax']);
    $faxes = explode(',', $fax_text);
    $variables['faxes'] = array_map('trim', $faxes);
  }

// Generates the output for the 'category_links' variable.
  if ($hcard['categories']) {
    $categories_text = check_plain($hcard['categories']);
    $categories = explode(',', $categories_text);
    $categories = array_map('trim', $categories);
    $category_links = array();
    foreach ($categories as $category) {
      $category_links[] = l($category, '<front>');
    }
    shuffle($category_links);
    $variables['category_links'] = $category_links;
  }
}

/**
 * hCard settings form.
 */
function hcard_admin_settings() {
  $default_values = variable_get('hcard', array());
  $form = array();
  $form['#tree'] = TRUE;
  $form['hcard']['fn_n'] = array(
    '#type' => 'fieldset',
    '#title' => t('Full Name'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );
  $form['hcard']['fn_n']['given-name'] = array(
    '#type' => 'textfield',
    '#title' => t('First Name'),
    '#default_value' => $default_values['fn_n']['given-name'],
    '#description' => 'given-name',
  );
  $form['hcard']['fn_n']['family-name'] = array(
    '#type' => 'textfield',
    '#title' => t('Last Name'),
    '#default_value' => $default_values['fn_n']['family-name'],
    '#description' => 'family-name',
  );
  $form['hcard']['org'] = array(
    '#type' => 'textfield',
    '#title' => t('Business Name'),
    '#default_value' => $default_values['org'],
    '#description' => 'org',
    '#required' => TRUE,
  );
  $form['hcard']['tagline'] = array(
    '#type' => 'fieldset',
    '#title' => t('Tagline'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#description' => t('(Examples below will produce: "Locally owned and serving !1, !2, and all of !3.")', array('!1' => l('Woodland', '<front>'), '!2' => l('the community', '<front>'), '!3' => l('Yolo County CA', '<front>'), )),
  );
  $form['hcard']['tagline']['tag'] = array(
    '#type' => 'textfield',
    '#title' => t('Tagline'),
    '#default_value' => $default_values['tagline']['tag'],
    '#description' => t('Use tokens !1, !2, !3, etc. that will be replaced by the items in the keyword list below. (Example: "Locally owned and serving !1, !2, and all of !3.")'),
  );
  $form['hcard']['tagline']['tag_list'] = array(
    '#type' => 'textfield',
    '#title' => t('Tagline Keywords'),
    '#default_value' => $default_values['tagline']['tag_list'],
    '#description' => t('Enter your keywords, separated by commas. (Example: "Woodland, the community, Yolo County CA")'),
  );
  $form['hcard']['adr'] = array(
    '#type' => 'fieldset',
    '#title' => t('Address'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#required' => TRUE,
  );
  $form['hcard']['adr']['street-address'] = array(
    '#type' => 'textfield',
    '#title' => t('Street Address'),
    '#default_value' => $default_values['adr']['street-address'],
    '#description' => 'street-address',
    '#required' => TRUE,
  );
  $form['hcard']['adr']['locality'] = array(
    '#type' => 'textfield',
    '#title' => t('City'),
    '#default_value' => $default_values['adr']['locality'],
    '#description' => 'locality',
    '#required' => TRUE,
  );
  $form['hcard']['adr']['region'] = array(
    '#type' => 'textfield',
    '#title' => t('State'),
    '#default_value' => $default_values['adr']['region'],
    '#description' => 'region',
    '#size' => 2,
    '#required' => TRUE,
  );
  $form['hcard']['adr']['postal-code'] = array(
    '#type' => 'textfield',
    '#title' => t('Postal Code +4'),
    '#default_value' => $default_values['adr']['postal-code'],
    '#description' => 'postal-code',
    '#size' => 10,
    '#required' => TRUE,
  );
  $form['hcard']['adr']['country-name'] = array(
    '#type' => 'textfield',
    '#title' => t('Country Name'),
    '#default_value' => $default_values['adr']['country-name'],
    '#description' => 'country-name',
    '#required' => TRUE,
  );
  $form['hcard']['longitude'] = array(
    '#type' => 'textfield',
    '#title' => t('Longitude'),
    '#default_value' => $default_values['longitude'],
    '#description' => 'longitude in full decimal format (like -121.629562)',
    '#required' => TRUE,
  );
  $form['hcard']['latitude'] = array(
    '#type' => 'textfield',
    '#title' => t('Latitude'),
    '#default_value' => $default_values['latitude'],
    '#description' => 'latitude in full decimal format (like 38.827382)',
    '#required' => TRUE,
  );
  $form['hcard']['phone'] = array(
    '#type' => 'fieldset',
    '#title' => t('Phones'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );
  $form['hcard']['phone']['voice'] = array(
    '#type' => 'textfield',
    '#title' => t('Voice Phone Number(s)'),
    '#default_value' => $default_values['phone']['voice'],
    '#description' => 'voice phone numbers, separated by commas',
  );
  $form['hcard']['phone']['fax'] = array(
    '#type' => 'textfield',
    '#title' => t('FAX Number(s)'),
    '#default_value' => $default_values['phone']['fax'],
    '#description' => 'fax numbers, separated by commas',
  );
  $form['hcard']['categories'] = array(
    '#type' => 'textfield',
    '#title' => t('Business Categories'),
    '#default_value' => $default_values['categories'],
    '#description' => t('Enter your business categories, separated by commas.'),
  );

  return system_settings_form($form);
}

/**
 * Implementation of hook_block().
 */
function hcard_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks[0] = array(
        'info' => 'hCard',
        'weight' => 10,
        'enabled' => 1,
        'region' => 'footer'
      );
      return $blocks;
    case 'view':
      $block = array();
      switch ($delta) {
        case 0:
          $hcard = variable_get('hcard', array());
          if ($hcard) {
            $block = array(
              'subject' => '',
              'content' => theme('hcard', $hcard),
            );
          }
        return $block;
      }
  }

}

/**
 * Theme function for the hcard system settings form.
 * It's just a wrapper so that themers can do what they want with this form.
 */
function theme_hcard_admin_settings($form) {
  return drupal_render($form);
}

/**
 * Convert a decimal-degree longitude or latitude point into degrees and decimal minutes.
 *
 * @param $decimal Decimal value for a longitude or latitude point.
 * @param $direction 'longitude' or 'latitude' are the only acceptable inputs.
 *
 * @return Text string containing a single character for N, S, E, or W, the degrees as whole number,
 *          and minutes as a decimal value.
 */
function hcard_coord_convert($decimal, $direction) {

  $decimal = floatval($decimal);
  if (!$decimal) {
    return FALSE;
  }
  switch ($direction) {
    case 'longitude':
      $coord_direction = ($decimal < 0) ? 'W' : 'E';
      break;
    case 'latitude':
      $coord_direction = ($decimal < 0) ? 'S' : 'N';
      break;
    default:
      return FALSE;
  }

  $coord_degrees = intval($decimal);
  $coord_minutes = abs(fmod($decimal, 1) * 60);

  return $coord_direction .' '. $coord_degrees .'° '. $coord_minutes .'"';
}